# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04b55d60f59f507feae0cf31699c649ea2e42a27fe2d776a7980efe5f97f229b2558be3278e0730eb09fe8e11767492b48874b3476a37d7d5fb02448b79cfed7

test:
  secret_key_base: 46431940bfd5e4b06eebee4781c901be54d237c7093eb84a9dc89044a3597e9c4135fec363747cec55c21627c849eaff2e5d80562a65b6ac427f9062902e0b08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
